FROM public.ecr.aws/lambda/python:3.13

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt -t ${LAMBDA_TASK_ROOT}

COPY main.py ${LAMBDA_TASK_ROOT}/
COPY routers/ ${LAMBDA_TASK_ROOT}/routers/
COPY services/ ${LAMBDA_TASK_ROOT}/services/
COPY schemas/ ${LAMBDA_TASK_ROOT}/schemas/

CMD ["main.handler"]
